name: Branch

on:
  workflow_dispatch:
  push:
    branches:
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup job workspace
        uses: ServerlessOpsIO/gha-setup-workspace@v1

      - name: Schema Validation
        id: schema-validation
        uses: dsanders11/json-schema-validate-action@v1.2.0
        with:
          files: 'action.yaml'
          schema: https://json.schemastore.org/github-action.json